---
abstract: 'make HTML5 DOM trees less insane'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Signature: 0.66
  Test::More: 0.61
  XML::LibXML::Debugging: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - HTML
  - HTML5
  - Markup
  - Fixer
  - Fix
  - Attributes
  - Namespaces
  - XML
  - DOM
  - Lang
  - Language
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-HTML5-Sanity
no_index:
  directory:
    - inc
    - t
requires:
  Locale::Country: 1.06
  XML::LibXML: 1.60
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Sanity
  homepage: http://search.cpan.org/dist/HTML-HTML5-Sanity/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/HTML-HTML5-Sanity/
version: 0.101
