@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/HTML-HTML5-Sanity/project>
	deps:runtime-recommendation      [ deps:on "HTML::HTML5::Parser 0.107"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "XML::LibXML 1.70"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Locale::Country"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "XML::LibXML::Debugging"^^deps:CpanId ].

